# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np

In [ ]:
a = np.random.uniform(0, 20,(4, 7))

print(a,'\n')

a = (a-a.min())/(a.max()-a.min())

print(a)

[[ 1.87075604  5.80698623 10.43891259  2.28231465  3.23758749  6.08561646
   7.04129339]
 [ 9.06216228 18.93702693  3.45115162  7.8824202   6.00049585 12.03135076
   6.62387362]
 [ 1.20884232 10.24714207 11.04840699  6.29010304  8.97997808  7.25116414
   1.89296543]
 [ 0.18223429 14.61874161 15.33751617  7.74798969 19.49739957  4.5666768
   6.40310885]] 

[[0.08741948 0.2912091  0.53101685 0.10872702 0.15818416 0.30563457
  0.35511263]
 [0.45973865 0.97098794 0.16924097 0.39866011 0.30122763 0.61346182
  0.33350164]
 [0.05315036 0.52108836 0.56257208 0.31622141 0.45548374 0.36597822
  0.08856932]
 [0.         0.74741826 0.78463123 0.39170027 1.         0.22699482
  0.32207203]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
a = np.random.randint(0, 10, size = (8, 10))

print(a,'\n')

b = np.sum(a, axis = 1)

print(b,'\n')

print(a[b.argmin()],b.argmin())


[[6 4 0 0 3 7 6 2 5 1]
 [1 1 8 6 6 0 5 8 8 6]
 [3 0 4 0 4 5 2 5 0 6]
 [9 3 2 2 0 4 6 5 3 8]
 [5 0 0 6 0 4 1 0 0 9]
 [0 7 5 4 1 9 6 9 4 6]
 [6 3 9 1 0 2 2 3 5 4]
 [4 8 6 5 8 6 5 1 6 9]] 

[34 49 29 42 25 51 35 58] 

[5 0 0 6 0 4 1 0 0 9] 4


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D


In [ ]:
size = int(input('Enter number of dimensions\n'))

A,B = np.random.random(size)*size,np.random.random(size)*size 

ans = np.linalg.norm(A-B)

print(ans)

Enter number of dimensions
3
2.9994048274562295


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B=np.array([[3, -1], [2, 1]])
C=np.array([[7, 21], [11, 8], [8, 4]])

X = np.matmul(np.matmul(np.linalg.matrix_power(A,-1),-C),np.linalg.matrix_power(B,-1))

print(X)

[[ 1.00000000e+00  5.55111512e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
# 1 
a = np.loadtxt('minutes_n_ingredients.csv',delimiter=',',dtype=np.int32,skiprows=1)

print(a[:5],a.shape,sep='\n')

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]
(100000, 3)


In [ ]:
# 2 

b = a[:,1:]

avg,mx,mn,med = np.average(b,axis=0),np.max(b,axis=0),np.min(b,axis=0),np.median(b,axis=0)

print(avg,mx,mn,med)

[2.16010017e+04 9.05528000e+00] [2147483647         39] [0 1] [40.  9.]


In [ ]:
# 3 
q = np.quantile(a[:,1], q=0.75)

a[:,1]=a[:,1].clip(max=q)

print(a.shape,a,sep='\n')

(100000, 3)
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


In [ ]:
# 4 
q = a[:,1]==0

count = np.where(q)[0].size

a[:,1][q] = 1
        
print(count,a,sep='\n')

479
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


In [ ]:
# 5 
number_of_uni = np.unique(a,axis=0).shape[0]

print(number_of_uni)

100000


In [ ]:
# 6 
uni = np.unique(a[:,2],return_counts=True)

print(uni,uni[0].size,sep='\n')


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39]), array([   13,   926,  2895,  5515,  7913,  9376, 10628, 10951, 10585,
        9591,  8297,  6605,  4997,  3663,  2595,  1767,  1246,   790,
         573,   376,   217,   161,   105,    69,    50,    28,    16,
          16,    12,    12,     3,     1,     2,     1,     3,     1,
           1], dtype=int64))
37


In [ ]:
# 7 
q = a[:,2]<=5

ingredients_not_gerater_than_five = a[np.where(q)]

print(ingredients_not_gerater_than_five.shape)

(17262, 3)


In [ ]:
# 8 

avg_ing_per_minute = a[:,2]/a[:,1]

maximum = avg_ing_per_minute.max()

print(avg_ing_per_minute,maximum,sep='\n')

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.21538462]
24.0


In [ ]:
# 9 

avg_n_ings_for_top_100_longest_in_cooking = np.average(a[np.argpartition(a[:,1],-100)[-100:]],axis = 0)[2]

print(avg_n_ings_for_top_100_longest_in_cooking)

9.96


In [ ]:
# 10 

print(a[np.random.choice(a.shape[0], 10, replace=False)])

[[238462      5      3]
 [ 30541     40      9]
 [246486     65     11]
 [138400     65     13]
 [292402     65     11]
 [337396     45      7]
 [261673      2     10]
 [151038     65      8]
 [396023     15      4]
 [ 49696     10      5]]


In [ ]:
# 11 
q = a[:,2] < avg[1]

percentage = 100*a[q].shape[0]/a.shape[0]

print(percentage)

58.802


In [ ]:
# 12 
ds = np.concatenate((a,np.array([[int(i<=20 and k<=5) for i,k in a[:,1:]]]).T),axis=1)

print(ds)


[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


In [ ]:
# 13 
q = ds[:,3] == 1

percentage_of_simples = 100*a[q].shape[0]/a.shape[0]

print(percentage_of_simples)


9.552


In [ ]:
# № 14 


short = a[:,1] < 10
standart = np.all([a[:,1] > 10,a[:,1] < 20],axis = 0)
long = a[:,1] >= 20

short_arr = a[short]
standart_arr = a[standart]
long_arr = a[long]


max_ings = min(short_arr.shape[0],standart_arr.shape[0],long_arr.shape[0])

list_3D = np.stack((short_arr[:max_ings],standart_arr[:max_ings],long_arr[:max_ings]),axis=0)

print(list_3D.shape)

(3, 7588, 3)
